### ISSUE TITLE
feat: SecurityConfig에 CORS 설정 활성화

### ISSUE THREAD

**Issue by cokid1998** [jongbinchoi/coffeeSubscription#12]
`SecurityConfig.java`
`.httpBasic(httpBasic -> httpBasic.disable()) // HTTP Basic 인증 비활성화`밑에
`.cors(cors -> cors.configurationSource(corsConfigurationSource()))`이 코드 넣어주세요

**Comment by jongbinchoi** [comment]
확인했습니다
